FROM jrei/systemd-ubuntu:20.04

RUN apt -y update && apt -y upgrade \
    && apt -y install ssh sudo vim curl wget iproute2 iputils-ping \
    && apt clean && rm -f /etc/machine-id /var/lib/dbus/machine-id \
    && sed -i "s/^#PermitRootLogin.*$/PermitRootLogin yes/g" /etc/ssh/sshd_config \
    && sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list

COPY ./scripts/init-rootfs.sh /

WORKDIR /
EXPOSE 22
CMD ["/sbin/init"]
