FROM centos:8

RUN yum -y install systemd openssh-server openssh-clients openssl sudo vim wget \
    iproute git nc jq tmux man rsync python3 gcc gcc-c++  \
    && yum -y update \
    && yum clean all && rm -f /etc/machine-id /var/lib/dbus/machine-id \
    && sed -i "s/^#PermitRootLogin.*$/PermitRootLogin yes/g" /etc/ssh/sshd_config \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

WORKDIR /
EXPOSE 22
CMD ["/sbin/init"]
