FROM jrei/systemd-ubuntu:20.04

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && apt -y update && apt -y upgrade \
    && apt -y install ssh sudo vim curl wget iproute2 iputils-ping \
    && apt clean

COPY ./scripts/init-rootfs.sh /

WORKDIR /
EXPOSE 22
CMD ["/sbin/init"]
